Capitulo06.Labs.WebApi/Lab.MVC/Controllers/FaturasController.cs
using Lab.MVC.Data;
using Lab.MVC.Models;
using Newtonsoft.Json;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Lab.MVC.Controllers
{
    public class FaturasController : Controller
    {
        HttpClient client;

        public FaturasController()
        {
            if (client == null)
            {
                // aqui configuramos a chamada de API de pagamentos
                client = new HttpClient();
                client.BaseAddress = new Uri("http://localhost:59941/");
                client.DefaultRequestHeaders.Accept.Add(
                    new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("aplication/json"));

            }
        }

        //private IEnumerable ItensDao;

        // GET: Faturas
        public ActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public ActionResult EfetuarPagamento()
        {
            try
            {
                ViewBag.ListaDePedidos = new SelectList(ItensDao.ListarPedidos(), "NumeroPedido", "NomeCliente");
                return View();
            }
            catch (Exception ex)
            {

                ViewBag.MensagemErro = ex.Message;
                return View("_Erro");
            }
        }


        [HttpPost]
        public async Task<ActionResult> EfetuarPagamento(Fatura fatura)
        {

            try
            {
                //obtendo id do pedido
                int idPedido = PedidosDao.BuscarId(fatura.NumeroPedido);

                //obtendo a soma dos itens do pedido
                double totalPedido = ItensDao.ListarItensPorPedido(idPedido)
                .ToList().Sum(p => p.TotalItem);

                //completando o objeto Fatura
                fatura.Valor = totalPedido;
                fatura.Status = 1;

                //obtendo o conteúdo JSON a partir do objeto
                string json = JsonConvert.SerializeObject(fatura);

                //serializando o objeto
                HttpContent content = new StringContent(
                json, Encoding.Unicode, "application/json");

                //enviando o conteúdo serializado para o serviço
                var response = await client.PostAsync("api/pagamentos", content);

                if (response.IsSuccessStatusCode)
                {
                    return View("_Sucesso");
                }

                else
                {
                    throw new Exception(response.ReasonPhrase);
                }
            }

            catch (Exception ex)
            {
                ViewBag.MensagemErro = ex.Message;
                return View("_Erro");
            }
        }


        public async Task<ActionResult> ListarFaturas()
        {
            try
            {
                HttpResponseMessage response = client
                .GetAsync("api/pagamentos").Result;
                if (response.IsSuccessStatusCode)
                {
                    var resultado = await response.Content
                    .ReadAsStringAsync();
                    var lista = JsonConvert
                    .DeserializeObject<Fatura[]>(resultado)
                    .ToList();
                    return View(lista);
                }
                else
                {
                    throw new Exception(response.ReasonPhrase);
                }
            }
            catch (Exception ex)
            {
                ViewBag.MensagemErro = ex.Message;
                return View("_Erro");
             }
        }
    }
}

Capitulo06.Labs.WebApi/Lab.MVC/Controllers/ItensController.cs
using Lab.MVC.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab.MVC.Controllers
{
    public class ItensController : Controller
    {
        // GET: Itens
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Incluir(int? idPedido)
        {
            try
            {
                ViewBag.ListaDeProdutos = new SelectList(
                ProdutosDao.ListarProdutos(), "Id", "Descricao");
                ViewBag.ListaDePedidos = new SelectList(
                ItensDao.ListarPedidos(), "IdPedido", "NomeCliente");
                ViewBag.ListaDeItens = ItensDao.ListarItensPorPedido(idPedido);
                return View();
            }
            catch (Exception ex)
            {
                ViewBag.MensagemErro = ex.Message;
                return View("_Erro");

            }
        }
    }
}

Capitulo06.Labs.WebApi/Lab.MVC/Controllers/PedidosController.cs
using Lab.MVC.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab.MVC.Controllers
{
    public class PedidosController : Controller
    {

        // GET: Pedidos
        // GET: Pedidos
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Incluir()
        {
            ViewBag.ListaDeClientes = new SelectList(
            ClientesDAO.ListarClientes(), "Documento", "Nome");
            return View();
        }

        [HttpPost]
        public ActionResult Incluir(Pedido pedido)
        {
            pedido.Data = DateTime.Now;
            if (!ModelState.IsValid)
            {
                return Incluir();
            }
            try
            {
                PedidosDao.IncluirPedido(pedido);
                ViewBag.ListaDeClientes = new SelectList(
                ClientesDAO.ListarClientes(), "Documento", "Nome");
                return Redirect("/Pedidos/Listar?id=" + pedido.DocCliente);
            }
            catch (Exception ex)
            {
                ViewBag.MensagemErro = ex.Message;
                return View("_Erro");
            }


        }

        public ActionResult Listar(string id)
        {
            try
            {

                ViewBag.ListaDeClientes = new SelectList(ClientesDAO.ListarClientes(), "Documento", "Nome");
                return View(PedidosDao.ListarPedidos(id));
            }
            catch (Exception ex)
            {
                ViewBag.MensagemErro = ex.Message;
                return View("_Erro");
            }
        }

        public ActionResult Remover(int? id)
        {
            try
            {
                if (id == null)
                {
                    throw new Exception("Nenhum código fornecido");
                }

                var pedido = PedidosDao.BuscarPedido((int)id);

                if (pedido == null)
                {
                    throw new
                        Exception("Nenhum pedido encontrado");
                }

                var doc = pedido.DocCliente;

                PedidosDao.RemoverPedido(pedido);
                return Redirect("/Pedidos/Listar?id=" + doc);
            }
            catch (Exception ex)
            {

                ViewBag.MensagemError = ex.Message;
                return View("_Erro");
            }
        }


    }
}

Capitulo06.Labs.WebApi/Lab.MVC/Controllers/UsuariosController.cs
using Lab.MVC.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Lab.MVC.Controllers
{
    public class UsuariosController : Controller
    {
     
        [HttpGet]
        public ActionResult CriarUsuario()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CriarUsuario(UsuarioViewModel usuario)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                //criar usuario no identity
                //precisamos de uma instancia de userstore para depois criar um usermanager
                var usuarioStore = new UserStore<IdentityUser>();

                //criamos agora o objeto userManager para gerenciar os usuarios
                var usuarioManager = new UserManager<IdentityUser>(usuarioStore);

                // cria uma identidade do usuario
                var usuarioInfo = new IdentityUser()
                {
                    UserName = usuario.Nome
                };
                // cria usuario
                IdentityResult resultado = usuarioManager.Create(usuarioInfo, usuario.Senha);

                if (resultado.Succeeded)
                {
                    //Autentica e volta para pagina inicial
                    var autManager = System.Web.HttpContext.Current.GetOwinContext().Authentication;
                    var identidadeUsuario = usuarioManager.CreateIdentity(usuarioInfo, DefaultAuthenticationTypes.ApplicationCookie);
                    autManager.SignIn(new AuthenticationProperties() { }, identidadeUsuario);
                    return RedirectToAction("Index", "Home");
                }

                else
                {
                    throw new Exception(resultado.Errors.FirstOrDefault());
                }

            }
            catch (Exception ex)
            {

               ViewBag.MensagemErro = ex.Message;
                return View("_Erro");
            }
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel usuario, string returnUrl)
        {
            // recomendado o uso do model view state
            if (!ModelState.IsValid)
            {
                return View();
            }

            try
            {
                var usuarioStore = new UserStore<IdentityUser>();
                var usuarioManager = new UserManager<IdentityUser>(usuarioStore);

                var usuarioInfo = usuarioManager.Find(usuario.Nome, usuario.Senha);

                if (usuarioInfo != null)
                {
                    var autManager = System.Web.HttpContext.Current.GetOwinContext().Authentication;

                    var identidadeUsuario = usuarioManager.CreateIdentity(usuarioInfo, DefaultAuthenticationTypes.ApplicationCookie);

                    autManager.SignIn(new AuthenticationProperties() { IsPersistent = false }, identidadeUsuario);
                    return returnUrl == null ? Redirect("/Home/Index") : Redirect(returnUrl);
                }

                else
                {
                    throw new Exception("Usuário ou Senha invállidos");
                }

            }
            catch (Exception ex)
            {

                ViewBag.MensagemErro = ex.Message;
                return View("_Erro");
            }
        }


        [HttpGet]
        public ActionResult Logout()
        {
            var autManager = System.Web.HttpContext.Current.GetOwinContext().Authentication;
            autManager.SignOut();

            return RedirectToAction("Index", "Home");
        }

    }
}

Capitulo06.Labs.WebApi/Lab.MVC/Views/Shared/Erro.cshtml
@{
    ViewBag.Title = "Erro";
}



<div class="jumbotron">
    <h2 class="text-danger">Ocorreu o seguinte erro:</h2>
    <div class="alert alert-danger text-center">
        @ViewBag.MensagemErro
    </div>
</div>

Capitulo06.Labs.WebApi/Lab.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Vendas</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-danger">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">IMPACTA VENDAS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Clientes", "Index", "Clientes", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Produtos", "Index", "Produtos", null, new { @class = "nav-link" })
                        </li>

                        <li class="nav-item">
                            @Html.ActionLink("Lista de Pedidos", "Index", "Pedidos", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Item", "Index", "Itens", null, new { @class = "nav-link" })
                        </li>

                        <li class="nav-item">
                            @Html.ActionLink("Pagamentos", "Index", "Faturas", null, new { @class = "nav-link" })
                        </li>

                        <li class="nav-item">
                            @{Html.RenderPartial("_UsuarioPV"); }
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled">Disabled</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>



    </header>
    <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777" /></svg>

                <div class="container">
                    <div class="carousel-caption text-start">
                        <h1>Example headline.</h1>
                        <p>Some representative placeholder content for the first slide of the carousel.</p>
                        <p><a class="btn btn-lg btn-primary" href="#">Sign up today</a></p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777" /></svg>

                <div class="container">
                    <div class="carousel-caption">
                        <h1>Another example headline.</h1>
                        <p>Some representative placeholder content for the second slide of the carousel.</p>
                        <p><a class="btn btn-lg btn-primary" href="#">Learn more</a></p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777" /></svg>

                <div class="container">
                    <div class="carousel-caption text-end">
                        <h1>One more for good measure.</h1>
                        <p>Some representative placeholder content for the third slide of this carousel.</p>
                        <p><a class="btn btn-lg btn-primary" href="#">Browse gallery</a></p>
                    </div>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Gestão de Vendas</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Capitulo06.Labs.WebApi/Lab.MVC/Views/Shared/_Sucesso.cshtml
@{
    ViewBag.Title = "Erro";
}
<h2 class="text-success">Pagamento OK</h2>
<div class="alert alert-success text-center">
    Pagamento efetuado com sucesso!
</div>

Capitulo06.Labs.WebApi/Lab.MVC/Views/Shared/_UsuarioPV.cshtml
@if (Request.IsAuthenticated)
{
    <ul class="nav navbar-nav navbar-right">
        <li>
            @Html.ActionLink(" |Seja bem vindo " + User.Identity.Name, "Index", "Home", null, new { @class = "nav-link" })
        </li>
        <li>
            @Html.ActionLink("Logout", "Logout", "Usuarios", null, new { @class = "nav-link" })
        </li>
    </ul>
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li>
            @Html.ActionLink("Cadastrar-se", "CriarUsuario", "Usuarios", null, new { @class = "nav-link" })
        </li>
        <li>
            @Html.ActionLink("Login", "Login", "Usuarios", null, new { @class = "nav-link" })
        </li>
    </ul>
}